### ISSUE TITLE
Kanban Board Final Capstone Project

### ISSUE THREAD

**Issue by TechnoAndy** [soesandarwin2201/house-renting-backend#33]
Hi there, 

We are 5 members in our team: @soesandarwin2201, @anyepeter, @studiosnabeel, @Alabi12 and @TechnoAndy 

Github repo: https://github.com/soesandarwin2201/house-renting-backend

![image](https://user-images.githubusercontent.com/47176316/230441123-ee0845fc-2e87-44a9-8085-efddd7fb6b29.png)

**Comment by Meltrust** [comment]
Hi @TechnoAndy,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been pointed, and assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [x] In task #9 did you mean the `rswag` gem for your API documentation?

![image](https://user-images.githubusercontent.com/57421823/230445254-3eef94db-9dc1-4738-b4d9-fa07203dbcc5.png)

If this was a mistake, kindly correct this task description with the correct gem.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TechnoAndy** [comment]
Change has been done

**Comment by Meltrust** [comment]
Hi @TechnoAndy,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!





Congratulations! 🎉 

### To highlight

- Task #9 has been corrected✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
